title: Jane's Blog
author: Janegao011919
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  An adult，who is still growing and learning. Always on the way. 
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
